apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "postgres.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "postgres.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: postgres
    port: {{ .Values.service.port }}
    targetPort: postgres
    protocol: TCP
